/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTabsRouteImport } from './routes/demo/tabs'
import { Route as DemoSmsRouteImport } from './routes/demo/sms'
import { Route as DemoPurchaseRouteImport } from './routes/demo/purchase'
import { Route as DemoPosRouteImport } from './routes/demo/pos'
import { Route as DemoInventoryRouteImport } from './routes/demo/inventory'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as DemoCmsRouteImport } from './routes/demo/cms'
import { Route as AppHomeRouteRouteImport } from './routes/_app/home/route'
import { Route as AppHomeReportsRouteImport } from './routes/_app/home/reports'
import { Route as AppHomePurchasesRouteImport } from './routes/_app/home/purchases'
import { Route as AppHomePosRouteImport } from './routes/_app/home/pos'
import { Route as AppHomeCustomersRouteImport } from './routes/_app/home/customers'
import { Route as AppHomeInventoryIndexRouteImport } from './routes/_app/home/inventory/index'
import { Route as AppHomeDashboardIndexRouteImport } from './routes/_app/home/dashboard/index'
import { Route as AppHomeInventoryLowStockRouteImport } from './routes/_app/home/inventory/low-stock'
import { Route as AppHomeInventoryExpiringRouteImport } from './routes/_app/home/inventory/expiring'
import { Route as AppHomeInventoryCategoriesRouteImport } from './routes/_app/home/inventory/categories'
import { Route as AppHomeInventoryAllRouteImport } from './routes/_app/home/inventory/all'
import { Route as AppHomeDashboardOverviewRouteImport } from './routes/_app/home/dashboard/overview'
import { Route as AppHomeDashboardAlertsRouteImport } from './routes/_app/home/dashboard/alerts'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTabsRoute = DemoTabsRouteImport.update({
  id: '/demo/tabs',
  path: '/demo/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSmsRoute = DemoSmsRouteImport.update({
  id: '/demo/sms',
  path: '/demo/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPurchaseRoute = DemoPurchaseRouteImport.update({
  id: '/demo/purchase',
  path: '/demo/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosRoute = DemoPosRouteImport.update({
  id: '/demo/pos',
  path: '/demo/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoInventoryRoute = DemoInventoryRouteImport.update({
  id: '/demo/inventory',
  path: '/demo/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/demo/dashboard',
  path: '/demo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCmsRoute = DemoCmsRouteImport.update({
  id: '/demo/cms',
  path: '/demo/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRouteRoute = AppHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeReportsRoute = AppHomeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHomePurchasesRoute = AppHomePurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHomePosRoute = AppHomePosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHomeCustomersRoute = AppHomeCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHomeInventoryIndexRoute = AppHomeInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHomeDashboardIndexRoute = AppHomeDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHomeInventoryLowStockRoute =
  AppHomeInventoryLowStockRouteImport.update({
    id: '/inventory/low-stock',
    path: '/inventory/low-stock',
    getParentRoute: () => AppHomeRouteRoute,
  } as any)
const AppHomeInventoryExpiringRoute =
  AppHomeInventoryExpiringRouteImport.update({
    id: '/inventory/expiring',
    path: '/inventory/expiring',
    getParentRoute: () => AppHomeRouteRoute,
  } as any)
const AppHomeInventoryCategoriesRoute =
  AppHomeInventoryCategoriesRouteImport.update({
    id: '/inventory/categories',
    path: '/inventory/categories',
    getParentRoute: () => AppHomeRouteRoute,
  } as any)
const AppHomeInventoryAllRoute = AppHomeInventoryAllRouteImport.update({
  id: '/inventory/all',
  path: '/inventory/all',
  getParentRoute: () => AppHomeRouteRoute,
} as any)
const AppHomeDashboardOverviewRoute =
  AppHomeDashboardOverviewRouteImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AppHomeRouteRoute,
  } as any)
const AppHomeDashboardAlertsRoute = AppHomeDashboardAlertsRouteImport.update({
  id: '/dashboard/alerts',
  path: '/dashboard/alerts',
  getParentRoute: () => AppHomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRouteRouteWithChildren
  '/demo/cms': typeof DemoCmsRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/inventory': typeof DemoInventoryRoute
  '/demo/pos': typeof DemoPosRoute
  '/demo/purchase': typeof DemoPurchaseRoute
  '/demo/sms': typeof DemoSmsRoute
  '/demo/tabs': typeof DemoTabsRoute
  '/home/customers': typeof AppHomeCustomersRoute
  '/home/pos': typeof AppHomePosRoute
  '/home/purchases': typeof AppHomePurchasesRoute
  '/home/reports': typeof AppHomeReportsRoute
  '/home/dashboard/alerts': typeof AppHomeDashboardAlertsRoute
  '/home/dashboard/overview': typeof AppHomeDashboardOverviewRoute
  '/home/inventory/all': typeof AppHomeInventoryAllRoute
  '/home/inventory/categories': typeof AppHomeInventoryCategoriesRoute
  '/home/inventory/expiring': typeof AppHomeInventoryExpiringRoute
  '/home/inventory/low-stock': typeof AppHomeInventoryLowStockRoute
  '/home/dashboard/': typeof AppHomeDashboardIndexRoute
  '/home/inventory/': typeof AppHomeInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AppHomeRouteRouteWithChildren
  '/demo/cms': typeof DemoCmsRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/inventory': typeof DemoInventoryRoute
  '/demo/pos': typeof DemoPosRoute
  '/demo/purchase': typeof DemoPurchaseRoute
  '/demo/sms': typeof DemoSmsRoute
  '/demo/tabs': typeof DemoTabsRoute
  '/home/customers': typeof AppHomeCustomersRoute
  '/home/pos': typeof AppHomePosRoute
  '/home/purchases': typeof AppHomePurchasesRoute
  '/home/reports': typeof AppHomeReportsRoute
  '/home/dashboard/alerts': typeof AppHomeDashboardAlertsRoute
  '/home/dashboard/overview': typeof AppHomeDashboardOverviewRoute
  '/home/inventory/all': typeof AppHomeInventoryAllRoute
  '/home/inventory/categories': typeof AppHomeInventoryCategoriesRoute
  '/home/inventory/expiring': typeof AppHomeInventoryExpiringRoute
  '/home/inventory/low-stock': typeof AppHomeInventoryLowStockRoute
  '/home/dashboard': typeof AppHomeDashboardIndexRoute
  '/home/inventory': typeof AppHomeInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/home': typeof AppHomeRouteRouteWithChildren
  '/demo/cms': typeof DemoCmsRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/inventory': typeof DemoInventoryRoute
  '/demo/pos': typeof DemoPosRoute
  '/demo/purchase': typeof DemoPurchaseRoute
  '/demo/sms': typeof DemoSmsRoute
  '/demo/tabs': typeof DemoTabsRoute
  '/_app/home/customers': typeof AppHomeCustomersRoute
  '/_app/home/pos': typeof AppHomePosRoute
  '/_app/home/purchases': typeof AppHomePurchasesRoute
  '/_app/home/reports': typeof AppHomeReportsRoute
  '/_app/home/dashboard/alerts': typeof AppHomeDashboardAlertsRoute
  '/_app/home/dashboard/overview': typeof AppHomeDashboardOverviewRoute
  '/_app/home/inventory/all': typeof AppHomeInventoryAllRoute
  '/_app/home/inventory/categories': typeof AppHomeInventoryCategoriesRoute
  '/_app/home/inventory/expiring': typeof AppHomeInventoryExpiringRoute
  '/_app/home/inventory/low-stock': typeof AppHomeInventoryLowStockRoute
  '/_app/home/dashboard/': typeof AppHomeDashboardIndexRoute
  '/_app/home/inventory/': typeof AppHomeInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/demo/cms'
    | '/demo/dashboard'
    | '/demo/inventory'
    | '/demo/pos'
    | '/demo/purchase'
    | '/demo/sms'
    | '/demo/tabs'
    | '/home/customers'
    | '/home/pos'
    | '/home/purchases'
    | '/home/reports'
    | '/home/dashboard/alerts'
    | '/home/dashboard/overview'
    | '/home/inventory/all'
    | '/home/inventory/categories'
    | '/home/inventory/expiring'
    | '/home/inventory/low-stock'
    | '/home/dashboard/'
    | '/home/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/demo/cms'
    | '/demo/dashboard'
    | '/demo/inventory'
    | '/demo/pos'
    | '/demo/purchase'
    | '/demo/sms'
    | '/demo/tabs'
    | '/home/customers'
    | '/home/pos'
    | '/home/purchases'
    | '/home/reports'
    | '/home/dashboard/alerts'
    | '/home/dashboard/overview'
    | '/home/inventory/all'
    | '/home/inventory/categories'
    | '/home/inventory/expiring'
    | '/home/inventory/low-stock'
    | '/home/dashboard'
    | '/home/inventory'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/home'
    | '/demo/cms'
    | '/demo/dashboard'
    | '/demo/inventory'
    | '/demo/pos'
    | '/demo/purchase'
    | '/demo/sms'
    | '/demo/tabs'
    | '/_app/home/customers'
    | '/_app/home/pos'
    | '/_app/home/purchases'
    | '/_app/home/reports'
    | '/_app/home/dashboard/alerts'
    | '/_app/home/dashboard/overview'
    | '/_app/home/inventory/all'
    | '/_app/home/inventory/categories'
    | '/_app/home/inventory/expiring'
    | '/_app/home/inventory/low-stock'
    | '/_app/home/dashboard/'
    | '/_app/home/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DemoCmsRoute: typeof DemoCmsRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoInventoryRoute: typeof DemoInventoryRoute
  DemoPosRoute: typeof DemoPosRoute
  DemoPurchaseRoute: typeof DemoPurchaseRoute
  DemoSmsRoute: typeof DemoSmsRoute
  DemoTabsRoute: typeof DemoTabsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tabs': {
      id: '/demo/tabs'
      path: '/demo/tabs'
      fullPath: '/demo/tabs'
      preLoaderRoute: typeof DemoTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sms': {
      id: '/demo/sms'
      path: '/demo/sms'
      fullPath: '/demo/sms'
      preLoaderRoute: typeof DemoSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/purchase': {
      id: '/demo/purchase'
      path: '/demo/purchase'
      fullPath: '/demo/purchase'
      preLoaderRoute: typeof DemoPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/pos': {
      id: '/demo/pos'
      path: '/demo/pos'
      fullPath: '/demo/pos'
      preLoaderRoute: typeof DemoPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/inventory': {
      id: '/demo/inventory'
      path: '/demo/inventory'
      fullPath: '/demo/inventory'
      preLoaderRoute: typeof DemoInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/demo/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cms': {
      id: '/demo/cms'
      path: '/demo/cms'
      fullPath: '/demo/cms'
      preLoaderRoute: typeof DemoCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/home/reports': {
      id: '/_app/home/reports'
      path: '/reports'
      fullPath: '/home/reports'
      preLoaderRoute: typeof AppHomeReportsRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/purchases': {
      id: '/_app/home/purchases'
      path: '/purchases'
      fullPath: '/home/purchases'
      preLoaderRoute: typeof AppHomePurchasesRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/pos': {
      id: '/_app/home/pos'
      path: '/pos'
      fullPath: '/home/pos'
      preLoaderRoute: typeof AppHomePosRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/customers': {
      id: '/_app/home/customers'
      path: '/customers'
      fullPath: '/home/customers'
      preLoaderRoute: typeof AppHomeCustomersRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/inventory/': {
      id: '/_app/home/inventory/'
      path: '/inventory'
      fullPath: '/home/inventory/'
      preLoaderRoute: typeof AppHomeInventoryIndexRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/dashboard/': {
      id: '/_app/home/dashboard/'
      path: '/dashboard'
      fullPath: '/home/dashboard/'
      preLoaderRoute: typeof AppHomeDashboardIndexRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/inventory/low-stock': {
      id: '/_app/home/inventory/low-stock'
      path: '/inventory/low-stock'
      fullPath: '/home/inventory/low-stock'
      preLoaderRoute: typeof AppHomeInventoryLowStockRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/inventory/expiring': {
      id: '/_app/home/inventory/expiring'
      path: '/inventory/expiring'
      fullPath: '/home/inventory/expiring'
      preLoaderRoute: typeof AppHomeInventoryExpiringRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/inventory/categories': {
      id: '/_app/home/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/home/inventory/categories'
      preLoaderRoute: typeof AppHomeInventoryCategoriesRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/inventory/all': {
      id: '/_app/home/inventory/all'
      path: '/inventory/all'
      fullPath: '/home/inventory/all'
      preLoaderRoute: typeof AppHomeInventoryAllRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/dashboard/overview': {
      id: '/_app/home/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/home/dashboard/overview'
      preLoaderRoute: typeof AppHomeDashboardOverviewRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
    '/_app/home/dashboard/alerts': {
      id: '/_app/home/dashboard/alerts'
      path: '/dashboard/alerts'
      fullPath: '/home/dashboard/alerts'
      preLoaderRoute: typeof AppHomeDashboardAlertsRouteImport
      parentRoute: typeof AppHomeRouteRoute
    }
  }
}

interface AppHomeRouteRouteChildren {
  AppHomeCustomersRoute: typeof AppHomeCustomersRoute
  AppHomePosRoute: typeof AppHomePosRoute
  AppHomePurchasesRoute: typeof AppHomePurchasesRoute
  AppHomeReportsRoute: typeof AppHomeReportsRoute
  AppHomeDashboardAlertsRoute: typeof AppHomeDashboardAlertsRoute
  AppHomeDashboardOverviewRoute: typeof AppHomeDashboardOverviewRoute
  AppHomeInventoryAllRoute: typeof AppHomeInventoryAllRoute
  AppHomeInventoryCategoriesRoute: typeof AppHomeInventoryCategoriesRoute
  AppHomeInventoryExpiringRoute: typeof AppHomeInventoryExpiringRoute
  AppHomeInventoryLowStockRoute: typeof AppHomeInventoryLowStockRoute
  AppHomeDashboardIndexRoute: typeof AppHomeDashboardIndexRoute
  AppHomeInventoryIndexRoute: typeof AppHomeInventoryIndexRoute
}

const AppHomeRouteRouteChildren: AppHomeRouteRouteChildren = {
  AppHomeCustomersRoute: AppHomeCustomersRoute,
  AppHomePosRoute: AppHomePosRoute,
  AppHomePurchasesRoute: AppHomePurchasesRoute,
  AppHomeReportsRoute: AppHomeReportsRoute,
  AppHomeDashboardAlertsRoute: AppHomeDashboardAlertsRoute,
  AppHomeDashboardOverviewRoute: AppHomeDashboardOverviewRoute,
  AppHomeInventoryAllRoute: AppHomeInventoryAllRoute,
  AppHomeInventoryCategoriesRoute: AppHomeInventoryCategoriesRoute,
  AppHomeInventoryExpiringRoute: AppHomeInventoryExpiringRoute,
  AppHomeInventoryLowStockRoute: AppHomeInventoryLowStockRoute,
  AppHomeDashboardIndexRoute: AppHomeDashboardIndexRoute,
  AppHomeInventoryIndexRoute: AppHomeInventoryIndexRoute,
}

const AppHomeRouteRouteWithChildren = AppHomeRouteRoute._addFileChildren(
  AppHomeRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppHomeRouteRoute: typeof AppHomeRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHomeRouteRoute: AppHomeRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DemoCmsRoute: DemoCmsRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoInventoryRoute: DemoInventoryRoute,
  DemoPosRoute: DemoPosRoute,
  DemoPurchaseRoute: DemoPurchaseRoute,
  DemoSmsRoute: DemoSmsRoute,
  DemoTabsRoute: DemoTabsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
