/**
 * Product data service (INTERNAL)
 * Handles product catalog data fetching
 *
 * @internal - Do not import directly, use hooks from main index
 */

import {
  productStockSummarySchema,
  productStockSummariesArraySchema,
  type ProductStockSummary,
} from "../schema";

// Mock products with aggregated stock summary
const MOCK_PRODUCT_SUMMARIES: ProductStockSummary[] = [
  {
    id: 1,
    name: "Amoxicillin 500mg",
    sku: "AMX-500",
    genericName: "Amoxicillin",
    manufacturer: "PharmaCorp",
    categoryId: 1,
    defaultSupplierId: 1,
    basePrice: 12.5,
    reorderLevel: 50,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Antibiotic for bacterial infections",
    isActive: true,
    category: {
      id: 1,
      name: "Antibiotic",
      description: "Antibacterial medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 1,
      name: "MedSupply Co",
      contactPerson: "John Smith",
      email: "john@medsupply.com",
      phone: "+1-555-0101",
      address: null,
      isActive: true,
    },
    totalQuantity: 240,
    availableQuantity: 240,
    reservedQuantity: 0,
    nearestExpiry: "2026-03-15",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 2,
    name: "Paracetamol 650mg",
    sku: "PCT-650",
    genericName: "Acetaminophen",
    manufacturer: "GenMed",
    categoryId: 2,
    defaultSupplierId: 2,
    basePrice: 4.2,
    reorderLevel: 100,
    requiresPrescription: false,
    controlledSubstance: false,
    description: "Pain reliever and fever reducer",
    isActive: true,
    category: {
      id: 2,
      name: "Analgesic",
      description: "Pain relief medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 2,
      name: "PharmGen",
      contactPerson: "Sarah Johnson",
      email: "sarah@pharmgen.com",
      phone: "+1-555-0102",
      address: null,
      isActive: true,
    },
    totalQuantity: 18,
    availableQuantity: 18,
    reservedQuantity: 0,
    nearestExpiry: "2025-09-20",
    batchCount: 1,
    stockStatus: "low",
  },
  {
    id: 3,
    name: "Metformin 500mg",
    sku: "MET-500",
    genericName: "Metformin HCl",
    manufacturer: "DiabetesCare",
    categoryId: 3,
    defaultSupplierId: 3,
    basePrice: 8.75,
    reorderLevel: 75,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Type 2 diabetes management",
    isActive: true,
    category: {
      id: 3,
      name: "Antidiabetic",
      description: "Diabetes management",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 3,
      name: "GeneriCo",
      contactPerson: "Mike Davis",
      email: "mike@generico.com",
      phone: "+1-555-0103",
      address: null,
      isActive: true,
    },
    totalQuantity: 302,
    availableQuantity: 302,
    reservedQuantity: 0,
    nearestExpiry: "2026-08-10",
    batchCount: 3,
    stockStatus: "ok",
  },
  {
    id: 4,
    name: "Omeprazole 20mg",
    sku: "OMZ-020",
    genericName: "Omeprazole",
    manufacturer: "GastroMed",
    categoryId: 4,
    defaultSupplierId: 1,
    basePrice: 15.0,
    reorderLevel: 60,
    requiresPrescription: false,
    controlledSubstance: false,
    description: "Proton pump inhibitor for acid reflux",
    isActive: true,
    category: {
      id: 4,
      name: "GI",
      description: "Gastrointestinal medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 1,
      name: "MedSupply Co",
      contactPerson: "John Smith",
      email: "john@medsupply.com",
      phone: "+1-555-0101",
      address: null,
      isActive: true,
    },
    totalQuantity: 85,
    availableQuantity: 85,
    reservedQuantity: 0,
    nearestExpiry: "2025-06-30",
    batchCount: 2,
    stockStatus: "expiring",
  },
  {
    id: 5,
    name: "Atorvastatin 10mg",
    sku: "ATV-010",
    genericName: "Atorvastatin Calcium",
    manufacturer: "CardioPharm",
    categoryId: 5,
    defaultSupplierId: 4,
    basePrice: 22.3,
    reorderLevel: 40,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Cholesterol-lowering statin",
    isActive: true,
    category: {
      id: 5,
      name: "Statin",
      description: "Cholesterol management",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 0,
    availableQuantity: 0,
    reservedQuantity: 0,
    nearestExpiry: null,
    batchCount: 0,
    stockStatus: "out",
  },
  {
    id: 6,
    name: "Lisinopril 5mg",
    sku: "LSN-005",
    genericName: "Lisinopril",
    manufacturer: "CardioPharm",
    categoryId: 6,
    defaultSupplierId: 4,
    basePrice: 9.9,
    reorderLevel: 50,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "ACE inhibitor for hypertension",
    isActive: true,
    category: {
      id: 6,
      name: "ACE Inhibitor",
      description: "Blood pressure management",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 145,
    availableQuantity: 145,
    reservedQuantity: 0,
    nearestExpiry: "2027-01-15",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 7,
    name: "Cetirizine 10mg",
    sku: "CTZ-010",
    genericName: "Cetirizine HCl",
    manufacturer: "AllergyRx",
    categoryId: 7,
    defaultSupplierId: 5,
    basePrice: 6.4,
    reorderLevel: 30,
    requiresPrescription: false,
    controlledSubstance: false,
    description: "Antihistamine for allergies",
    isActive: true,
    category: {
      id: 7,
      name: "Antihistamine",
      description: "Allergy relief",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 5,
      name: "AllergyRx",
      contactPerson: "Tom Wilson",
      email: "tom@allergyrx.com",
      phone: "+1-555-0105",
      address: null,
      isActive: true,
    },
    totalQuantity: 12,
    availableQuantity: 12,
    reservedQuantity: 0,
    nearestExpiry: "2025-08-20",
    batchCount: 1,
    stockStatus: "low",
  },
  {
    id: 8,
    name: "Azithromycin 250mg",
    sku: "AZT-250",
    genericName: "Azithromycin",
    manufacturer: "PharmGen",
    categoryId: 1,
    defaultSupplierId: 2,
    basePrice: 18.6,
    reorderLevel: 40,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Macrolide antibiotic",
    isActive: true,
    category: {
      id: 1,
      name: "Antibiotic",
      description: "Antibacterial medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 2,
      name: "PharmGen",
      contactPerson: "Sarah Johnson",
      email: "sarah@pharmgen.com",
      phone: "+1-555-0102",
      address: null,
      isActive: true,
    },
    totalQuantity: 67,
    availableQuantity: 67,
    reservedQuantity: 0,
    nearestExpiry: "2025-05-10",
    batchCount: 2,
    stockStatus: "expiring",
  },
  {
    id: 9,
    name: "Ibuprofen 400mg",
    sku: "IBU-400",
    genericName: "Ibuprofen",
    manufacturer: "GeneriCo",
    categoryId: 8,
    defaultSupplierId: 3,
    basePrice: 5.1,
    reorderLevel: 80,
    requiresPrescription: false,
    controlledSubstance: false,
    description: "NSAID for pain and inflammation",
    isActive: true,
    category: {
      id: 8,
      name: "NSAID",
      description: "Anti-inflammatory",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 3,
      name: "GeneriCo",
      contactPerson: "Mike Davis",
      email: "mike@generico.com",
      phone: "+1-555-0103",
      address: null,
      isActive: true,
    },
    totalQuantity: 389,
    availableQuantity: 389,
    reservedQuantity: 0,
    nearestExpiry: "2027-03-25",
    batchCount: 4,
    stockStatus: "ok",
  },
  {
    id: 10,
    name: "Losartan 50mg",
    sku: "LST-050",
    genericName: "Losartan Potassium",
    manufacturer: "CardioPharm",
    categoryId: 9,
    defaultSupplierId: 4,
    basePrice: 11.2,
    reorderLevel: 50,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "ARB for hypertension",
    isActive: true,
    category: {
      id: 9,
      name: "ARB",
      description: "Angiotensin receptor blocker",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 203,
    availableQuantity: 203,
    reservedQuantity: 0,
    nearestExpiry: "2026-06-18",
    batchCount: 3,
    stockStatus: "ok",
  },
  {
    id: 11,
    name: "Pantoprazole 40mg",
    sku: "PNT-040",
    genericName: "Pantoprazole",
    manufacturer: "GastroMed",
    categoryId: 4,
    defaultSupplierId: 1,
    basePrice: 19.8,
    reorderLevel: 45,
    requiresPrescription: false,
    controlledSubstance: false,
    description: "Proton pump inhibitor",
    isActive: true,
    category: {
      id: 4,
      name: "GI",
      description: "Gastrointestinal medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 1,
      name: "MedSupply Co",
      contactPerson: "John Smith",
      email: "john@medsupply.com",
      phone: "+1-555-0101",
      address: null,
      isActive: true,
    },
    totalQuantity: 7,
    availableQuantity: 7,
    reservedQuantity: 0,
    nearestExpiry: "2025-07-12",
    batchCount: 1,
    stockStatus: "low",
  },
  {
    id: 12,
    name: "Sertraline 50mg",
    sku: "SRT-050",
    genericName: "Sertraline HCl",
    manufacturer: "NeuroPharma",
    categoryId: 10,
    defaultSupplierId: 6,
    basePrice: 28.5,
    reorderLevel: 35,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "SSRI antidepressant",
    isActive: true,
    category: {
      id: 10,
      name: "SSRI",
      description: "Selective serotonin reuptake inhibitor",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 6,
      name: "NeuroPharma",
      contactPerson: "Lisa Chen",
      email: "lisa@neuropharma.com",
      phone: "+1-555-0106",
      address: null,
      isActive: true,
    },
    totalQuantity: 94,
    availableQuantity: 94,
    reservedQuantity: 0,
    nearestExpiry: "2026-10-05",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 13,
    name: "Levothyroxine 100mcg",
    sku: "LVT-100",
    genericName: "Levothyroxine Sodium",
    manufacturer: "EndoMed",
    categoryId: 11,
    defaultSupplierId: 7,
    basePrice: 14.3,
    reorderLevel: 60,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Thyroid hormone replacement",
    isActive: true,
    category: {
      id: 11,
      name: "Thyroid",
      description: "Thyroid medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 7,
      name: "EndoMed",
      contactPerson: "Robert Lee",
      email: "robert@endomed.com",
      phone: "+1-555-0107",
      address: null,
      isActive: true,
    },
    totalQuantity: 156,
    availableQuantity: 156,
    reservedQuantity: 0,
    nearestExpiry: "2026-11-20",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 14,
    name: "Amlodipine 5mg",
    sku: "AML-005",
    genericName: "Amlodipine Besylate",
    manufacturer: "CardioPharm",
    categoryId: 12,
    defaultSupplierId: 4,
    basePrice: 7.8,
    reorderLevel: 55,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Calcium channel blocker",
    isActive: true,
    category: {
      id: 12,
      name: "CCB",
      description: "Calcium channel blocker",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 0,
    availableQuantity: 0,
    reservedQuantity: 0,
    nearestExpiry: null,
    batchCount: 0,
    stockStatus: "out",
  },
  {
    id: 15,
    name: "Gabapentin 300mg",
    sku: "GBP-300",
    genericName: "Gabapentin",
    manufacturer: "NeuroPharma",
    categoryId: 13,
    defaultSupplierId: 6,
    basePrice: 16.7,
    reorderLevel: 40,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Anticonvulsant for nerve pain",
    isActive: true,
    category: {
      id: 13,
      name: "Anticonvulsant",
      description: "Seizure and nerve pain",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 6,
      name: "NeuroPharma",
      contactPerson: "Lisa Chen",
      email: "lisa@neuropharma.com",
      phone: "+1-555-0106",
      address: null,
      isActive: true,
    },
    totalQuantity: 78,
    availableQuantity: 78,
    reservedQuantity: 0,
    nearestExpiry: "2026-04-30",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 16,
    name: "Montelukast 10mg",
    sku: "MTL-010",
    genericName: "Montelukast Sodium",
    manufacturer: "AllergyRx",
    categoryId: 14,
    defaultSupplierId: 5,
    basePrice: 21.4,
    reorderLevel: 30,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Leukotriene receptor antagonist",
    isActive: true,
    category: {
      id: 14,
      name: "Respiratory",
      description: "Asthma and allergy",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 5,
      name: "AllergyRx",
      contactPerson: "Tom Wilson",
      email: "tom@allergyrx.com",
      phone: "+1-555-0105",
      address: null,
      isActive: true,
    },
    totalQuantity: 15,
    availableQuantity: 15,
    reservedQuantity: 0,
    nearestExpiry: "2025-09-08",
    batchCount: 1,
    stockStatus: "low",
  },
  {
    id: 17,
    name: "Prednisone 20mg",
    sku: "PRD-020",
    genericName: "Prednisone",
    manufacturer: "GeneriCo",
    categoryId: 15,
    defaultSupplierId: 3,
    basePrice: 8.9,
    reorderLevel: 50,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Corticosteroid anti-inflammatory",
    isActive: true,
    category: {
      id: 15,
      name: "Corticosteroid",
      description: "Anti-inflammatory steroid",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 3,
      name: "GeneriCo",
      contactPerson: "Mike Davis",
      email: "mike@generico.com",
      phone: "+1-555-0103",
      address: null,
      isActive: true,
    },
    totalQuantity: 112,
    availableQuantity: 112,
    reservedQuantity: 0,
    nearestExpiry: "2026-07-22",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 18,
    name: "Warfarin 5mg",
    sku: "WRF-005",
    genericName: "Warfarin Sodium",
    manufacturer: "CardioPharm",
    categoryId: 16,
    defaultSupplierId: 4,
    basePrice: 13.2,
    reorderLevel: 40,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Anticoagulant blood thinner",
    isActive: true,
    category: {
      id: 16,
      name: "Anticoagulant",
      description: "Blood thinner",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 89,
    availableQuantity: 89,
    reservedQuantity: 0,
    nearestExpiry: "2025-12-15",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 19,
    name: "Albuterol Inhaler",
    sku: "ALB-INH",
    genericName: "Albuterol Sulfate",
    manufacturer: "AllergyRx",
    categoryId: 14,
    defaultSupplierId: 5,
    basePrice: 32.5,
    reorderLevel: 25,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Bronchodilator for asthma",
    isActive: true,
    category: {
      id: 14,
      name: "Respiratory",
      description: "Asthma and allergy",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 5,
      name: "AllergyRx",
      contactPerson: "Tom Wilson",
      email: "tom@allergyrx.com",
      phone: "+1-555-0105",
      address: null,
      isActive: true,
    },
    totalQuantity: 43,
    availableQuantity: 43,
    reservedQuantity: 0,
    nearestExpiry: "2026-02-28",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 20,
    name: "Furosemide 40mg",
    sku: "FRS-040",
    genericName: "Furosemide",
    manufacturer: "CardioPharm",
    categoryId: 17,
    defaultSupplierId: 4,
    basePrice: 6.7,
    reorderLevel: 60,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Loop diuretic",
    isActive: true,
    category: {
      id: 17,
      name: "Diuretic",
      description: "Water pill",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 8,
    availableQuantity: 8,
    reservedQuantity: 0,
    nearestExpiry: "2025-06-05",
    batchCount: 1,
    stockStatus: "low",
  },
  {
    id: 21,
    name: "Clopidogrel 75mg",
    sku: "CLP-075",
    genericName: "Clopidogrel Bisulfate",
    manufacturer: "CardioPharm",
    categoryId: 18,
    defaultSupplierId: 4,
    basePrice: 24.8,
    reorderLevel: 35,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Antiplatelet agent",
    isActive: true,
    category: {
      id: 18,
      name: "Antiplatelet",
      description: "Blood clot prevention",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 67,
    availableQuantity: 67,
    reservedQuantity: 0,
    nearestExpiry: "2026-09-12",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 22,
    name: "Tramadol 50mg",
    sku: "TRM-050",
    genericName: "Tramadol HCl",
    manufacturer: "PharmaCorp",
    categoryId: 2,
    defaultSupplierId: 1,
    basePrice: 11.5,
    reorderLevel: 45,
    requiresPrescription: true,
    controlledSubstance: true,
    description: "Opioid pain reliever",
    isActive: true,
    category: {
      id: 2,
      name: "Analgesic",
      description: "Pain relief medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 1,
      name: "MedSupply Co",
      contactPerson: "John Smith",
      email: "john@medsupply.com",
      phone: "+1-555-0101",
      address: null,
      isActive: true,
    },
    totalQuantity: 0,
    availableQuantity: 0,
    reservedQuantity: 0,
    nearestExpiry: null,
    batchCount: 0,
    stockStatus: "out",
  },
  {
    id: 23,
    name: "Ranitidine 150mg",
    sku: "RNT-150",
    genericName: "Ranitidine HCl",
    manufacturer: "GastroMed",
    categoryId: 4,
    defaultSupplierId: 1,
    basePrice: 9.3,
    reorderLevel: 50,
    requiresPrescription: false,
    controlledSubstance: false,
    description: "H2 blocker for acid reduction",
    isActive: true,
    category: {
      id: 4,
      name: "GI",
      description: "Gastrointestinal medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 1,
      name: "MedSupply Co",
      contactPerson: "John Smith",
      email: "john@medsupply.com",
      phone: "+1-555-0101",
      address: null,
      isActive: true,
    },
    totalQuantity: 134,
    availableQuantity: 134,
    reservedQuantity: 0,
    nearestExpiry: "2026-12-08",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 24,
    name: "Ciprofloxacin 500mg",
    sku: "CPR-500",
    genericName: "Ciprofloxacin HCl",
    manufacturer: "PharmaCorp",
    categoryId: 1,
    defaultSupplierId: 1,
    basePrice: 17.9,
    reorderLevel: 40,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Fluoroquinolone antibiotic",
    isActive: true,
    category: {
      id: 1,
      name: "Antibiotic",
      description: "Antibacterial medications",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 1,
      name: "MedSupply Co",
      contactPerson: "John Smith",
      email: "john@medsupply.com",
      phone: "+1-555-0101",
      address: null,
      isActive: true,
    },
    totalQuantity: 56,
    availableQuantity: 56,
    reservedQuantity: 0,
    nearestExpiry: "2025-04-18",
    batchCount: 2,
    stockStatus: "expiring",
  },
  {
    id: 25,
    name: "Hydrochlorothiazide 25mg",
    sku: "HCT-025",
    genericName: "Hydrochlorothiazide",
    manufacturer: "CardioPharm",
    categoryId: 17,
    defaultSupplierId: 4,
    basePrice: 5.4,
    reorderLevel: 70,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Thiazide diuretic",
    isActive: true,
    category: {
      id: 17,
      name: "Diuretic",
      description: "Water pill",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 4,
      name: "CardioPharm",
      contactPerson: "Emily Brown",
      email: "emily@cardiopharm.com",
      phone: "+1-555-0104",
      address: null,
      isActive: true,
    },
    totalQuantity: 267,
    availableQuantity: 267,
    reservedQuantity: 0,
    nearestExpiry: "2027-05-14",
    batchCount: 3,
    stockStatus: "ok",
  },
  {
    id: 26,
    name: "Alprazolam 0.5mg",
    sku: "ALP-005",
    genericName: "Alprazolam",
    manufacturer: "NeuroPharma",
    categoryId: 19,
    defaultSupplierId: 6,
    basePrice: 19.2,
    reorderLevel: 30,
    requiresPrescription: true,
    controlledSubstance: true,
    description: "Benzodiazepine for anxiety",
    isActive: true,
    category: {
      id: 19,
      name: "Benzodiazepine",
      description: "Anxiety and sedation",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 6,
      name: "NeuroPharma",
      contactPerson: "Lisa Chen",
      email: "lisa@neuropharma.com",
      phone: "+1-555-0106",
      address: null,
      isActive: true,
    },
    totalQuantity: 11,
    availableQuantity: 11,
    reservedQuantity: 0,
    nearestExpiry: "2025-10-22",
    batchCount: 1,
    stockStatus: "low",
  },
  {
    id: 27,
    name: "Escitalopram 10mg",
    sku: "ESC-010",
    genericName: "Escitalopram Oxalate",
    manufacturer: "NeuroPharma",
    categoryId: 10,
    defaultSupplierId: 6,
    basePrice: 26.3,
    reorderLevel: 35,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "SSRI for depression and anxiety",
    isActive: true,
    category: {
      id: 10,
      name: "SSRI",
      description: "Selective serotonin reuptake inhibitor",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 6,
      name: "NeuroPharma",
      contactPerson: "Lisa Chen",
      email: "lisa@neuropharma.com",
      phone: "+1-555-0106",
      address: null,
      isActive: true,
    },
    totalQuantity: 98,
    availableQuantity: 98,
    reservedQuantity: 0,
    nearestExpiry: "2026-08-30",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 28,
    name: "Meloxicam 15mg",
    sku: "MLX-015",
    genericName: "Meloxicam",
    manufacturer: "GeneriCo",
    categoryId: 8,
    defaultSupplierId: 3,
    basePrice: 12.8,
    reorderLevel: 45,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "NSAID for arthritis",
    isActive: true,
    category: {
      id: 8,
      name: "NSAID",
      description: "Anti-inflammatory",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 3,
      name: "GeneriCo",
      contactPerson: "Mike Davis",
      email: "mike@generico.com",
      phone: "+1-555-0103",
      address: null,
      isActive: true,
    },
    totalQuantity: 76,
    availableQuantity: 76,
    reservedQuantity: 0,
    nearestExpiry: "2026-03-17",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 29,
    name: "Tamsulosin 0.4mg",
    sku: "TMS-004",
    genericName: "Tamsulosin HCl",
    manufacturer: "UroMed",
    categoryId: 20,
    defaultSupplierId: 8,
    basePrice: 22.7,
    reorderLevel: 30,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Alpha blocker for BPH",
    isActive: true,
    category: {
      id: 20,
      name: "Urological",
      description: "Urinary and prostate",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 8,
      name: "UroMed",
      contactPerson: "David Park",
      email: "david@uromed.com",
      phone: "+1-555-0108",
      address: null,
      isActive: true,
    },
    totalQuantity: 54,
    availableQuantity: 54,
    reservedQuantity: 0,
    nearestExpiry: "2026-11-09",
    batchCount: 2,
    stockStatus: "ok",
  },
  {
    id: 30,
    name: "Glipizide 5mg",
    sku: "GLP-005",
    genericName: "Glipizide",
    manufacturer: "DiabetesCare",
    categoryId: 3,
    defaultSupplierId: 3,
    basePrice: 10.4,
    reorderLevel: 50,
    requiresPrescription: true,
    controlledSubstance: false,
    description: "Sulfonylurea for diabetes",
    isActive: true,
    category: {
      id: 3,
      name: "Antidiabetic",
      description: "Diabetes management",
      parentCategoryId: null,
    },
    defaultSupplier: {
      id: 3,
      name: "GeneriCo",
      contactPerson: "Mike Davis",
      email: "mike@generico.com",
      phone: "+1-555-0103",
      address: null,
      isActive: true,
    },
    totalQuantity: 0,
    availableQuantity: 0,
    reservedQuantity: 0,
    nearestExpiry: null,
    batchCount: 0,
    stockStatus: "out",
  },
];

/**
 * Fetch all products with aggregated stock summary
 * TODO: Replace with actual API call
 *
 * @throws {Error} If data validation fails
 */
export async function fetchProductSummaries(): Promise<ProductStockSummary[]> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 300));

  // Validate data with Zod schema
  const result = productStockSummariesArraySchema.safeParse(
    MOCK_PRODUCT_SUMMARIES,
  );

  if (!result.success) {
    console.error("Product summary validation failed:", result.error);
    throw new Error("Invalid product summary data format");
  }

  return result.data;
}

/**
 * Fetch single product summary by ID
 * TODO: Replace with actual API call
 *
 * @throws {Error} If data validation fails
 */
export async function fetchProductSummaryById(
  id: number,
): Promise<ProductStockSummary | null> {
  await new Promise((resolve) => setTimeout(resolve, 200));

  const product = MOCK_PRODUCT_SUMMARIES.find((p) => p.id === id);

  if (!product) {
    return null;
  }

  // Validate single product with Zod schema
  const result = productStockSummarySchema.safeParse(product);

  if (!result.success) {
    console.error("Product summary validation failed:", result.error);
    throw new Error("Invalid product summary data format");
  }

  return result.data;
}
