/**
 * Transaction data service (INTERNAL)
 * Handles stock transaction data fetching
 *
 * @internal - Do not import directly, use hooks from main index
 */

import {
  stockTransactionWithRelationsSchema,
  stockTransactionsWithRelationsArraySchema,
  type StockTransactionWithRelations,
} from "../schema";

// Mock transactions - will be replaced with API calls
const MOCK_TRANSACTIONS: StockTransactionWithRelations[] = [
  // Product 1: Amoxicillin 500mg
  {
    id: 1,
    batchId: 1,
    type: "purchase",
    quantity: 150,
    orderId: null,
    userId: 1,
    reason: "Initial stock receipt",
    timestamp: "2024-01-10T10:00:00Z",
    batch: {
      id: 1,
      productId: 1,
      batchNumber: "AMX-2024-001",
      expiryDate: "2026-03-15",
      supplierId: 1,
      purchaseOrderId: 1001,
      receivedDate: "2024-01-10",
      costPerUnit: 10.0,
      quantityReceived: 150,
      quantityRemaining: 150,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-01-10T10:00:00Z",
      updatedAt: "2024-01-10T10:00:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 2,
    batchId: 1,
    type: "sale",
    quantity: -10,
    orderId: 5001,
    userId: 2,
    reason: null,
    timestamp: "2024-01-15T14:30:00Z",
    batch: {
      id: 1,
      productId: 1,
      batchNumber: "AMX-2024-001",
      expiryDate: "2026-03-15",
      supplierId: 1,
      purchaseOrderId: 1001,
      receivedDate: "2024-01-10",
      costPerUnit: 10.0,
      quantityReceived: 150,
      quantityRemaining: 140,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-01-10T10:00:00Z",
      updatedAt: "2024-01-15T14:30:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 12,
    batchId: 1,
    type: "sale",
    quantity: -5,
    orderId: 5007,
    userId: 2,
    reason: "Prescription order",
    timestamp: "2024-01-18T09:15:00Z",
    batch: {
      id: 1,
      productId: 1,
      batchNumber: "AMX-2024-001",
      expiryDate: "2026-03-15",
      supplierId: 1,
      purchaseOrderId: 1001,
      receivedDate: "2024-01-10",
      costPerUnit: 10.0,
      quantityReceived: 150,
      quantityRemaining: 135,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-01-10T10:00:00Z",
      updatedAt: "2024-01-18T09:15:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 13,
    batchId: 1,
    type: "adjustment",
    quantity: -3,
    orderId: null,
    userId: 1,
    reason: "Damaged units - quality check",
    timestamp: "2024-01-22T11:45:00Z",
    batch: {
      id: 1,
      productId: 1,
      batchNumber: "AMX-2024-001",
      expiryDate: "2026-03-15",
      supplierId: 1,
      purchaseOrderId: 1001,
      receivedDate: "2024-01-10",
      costPerUnit: 10.0,
      quantityReceived: 150,
      quantityRemaining: 132,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-01-10T10:00:00Z",
      updatedAt: "2024-01-22T11:45:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 14,
    batchId: 1,
    type: "sale",
    quantity: -8,
    orderId: 5008,
    userId: 3,
    reason: null,
    timestamp: "2024-01-25T14:20:00Z",
    batch: {
      id: 1,
      productId: 1,
      batchNumber: "AMX-2024-001",
      expiryDate: "2026-03-15",
      supplierId: 1,
      purchaseOrderId: 1001,
      receivedDate: "2024-01-10",
      costPerUnit: 10.0,
      quantityReceived: 150,
      quantityRemaining: 124,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-01-10T10:00:00Z",
      updatedAt: "2024-01-25T14:20:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 15,
    batchId: 2,
    type: "purchase",
    quantity: 100,
    orderId: null,
    userId: 1,
    reason: "Replenishment order",
    timestamp: "2024-02-01T08:00:00Z",
    batch: {
      id: 2,
      productId: 1,
      batchNumber: "AMX-2024-002",
      expiryDate: "2026-06-20",
      supplierId: 1,
      purchaseOrderId: 1005,
      receivedDate: "2024-02-01",
      costPerUnit: 9.5,
      quantityReceived: 100,
      quantityRemaining: 100,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-02-01T08:00:00Z",
      updatedAt: "2024-02-01T08:00:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 16,
    batchId: 2,
    type: "transfer",
    quantity: 20,
    orderId: null,
    userId: 1,
    reason: "Transfer from Branch: Downtown",
    timestamp: "2024-02-05T10:30:00Z",
    batch: {
      id: 2,
      productId: 1,
      batchNumber: "AMX-2024-002",
      expiryDate: "2026-06-20",
      supplierId: 1,
      purchaseOrderId: 1005,
      receivedDate: "2024-02-01",
      costPerUnit: 9.5,
      quantityReceived: 100,
      quantityRemaining: 120,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-02-01T08:00:00Z",
      updatedAt: "2024-02-05T10:30:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 17,
    batchId: 2,
    type: "sale",
    quantity: -12,
    orderId: 5009,
    userId: 2,
    reason: null,
    timestamp: "2024-02-10T15:45:00Z",
    batch: {
      id: 2,
      productId: 1,
      batchNumber: "AMX-2024-002",
      expiryDate: "2026-06-20",
      supplierId: 1,
      purchaseOrderId: 1005,
      receivedDate: "2024-02-01",
      costPerUnit: 9.5,
      quantityReceived: 100,
      quantityRemaining: 108,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-02-01T08:00:00Z",
      updatedAt: "2024-02-10T15:45:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 18,
    batchId: 2,
    type: "sale",
    quantity: -7,
    orderId: 5010,
    userId: 3,
    reason: null,
    timestamp: "2024-02-15T11:20:00Z",
    batch: {
      id: 2,
      productId: 1,
      batchNumber: "AMX-2024-002",
      expiryDate: "2026-06-20",
      supplierId: 1,
      purchaseOrderId: 1005,
      receivedDate: "2024-02-01",
      costPerUnit: 9.5,
      quantityReceived: 100,
      quantityRemaining: 101,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-02-01T08:00:00Z",
      updatedAt: "2024-02-15T11:20:00Z",
      product: {
        id: 1,
        name: "Amoxicillin 500mg",
        sku: "AMX-500",
        genericName: "Amoxicillin",
        manufacturer: "PharmaCorp",
        categoryId: 1,
        defaultSupplierId: 1,
        basePrice: 12.5,
        reorderLevel: 50,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Antibiotic for bacterial infections",
        isActive: true,
        category: {
          id: 1,
          name: "Antibiotic",
          description: "Antibacterial medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  // Product 2: Paracetamol 650mg
  {
    id: 3,
    batchId: 3,
    type: "purchase",
    quantity: 200,
    orderId: null,
    userId: 1,
    reason: "Stock replenishment",
    timestamp: "2023-12-05T09:00:00Z",
    batch: {
      id: 3,
      productId: 2,
      batchNumber: "PCT-2023-001",
      expiryDate: "2025-09-20",
      supplierId: 2,
      purchaseOrderId: 1002,
      receivedDate: "2023-12-05",
      costPerUnit: 3.5,
      quantityReceived: 200,
      quantityRemaining: 18,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2023-12-05T09:00:00Z",
      updatedAt: "2023-12-05T09:00:00Z",
      product: {
        id: 2,
        name: "Paracetamol 650mg",
        sku: "PCT-650",
        genericName: "Acetaminophen",
        manufacturer: "GenMed",
        categoryId: 2,
        defaultSupplierId: 2,
        basePrice: 4.2,
        reorderLevel: 100,
        requiresPrescription: false,
        controlledSubstance: false,
        description: "Pain reliever and fever reducer",
        isActive: true,
        category: {
          id: 2,
          name: "Analgesic",
          description: "Pain relief medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 2,
          name: "PharmGen",
          contactPerson: "Sarah Johnson",
          email: "sarah@pharmgen.com",
          phone: "+1-555-0102",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 2,
        name: "PharmGen",
        contactPerson: "Sarah Johnson",
        email: "sarah@pharmgen.com",
        phone: "+1-555-0102",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 4,
    batchId: 3,
    type: "sale",
    quantity: -50,
    orderId: 5002,
    userId: 2,
    reason: null,
    timestamp: "2024-01-08T11:20:00Z",
    batch: {
      id: 3,
      productId: 2,
      batchNumber: "PCT-2023-001",
      expiryDate: "2025-09-20",
      supplierId: 2,
      purchaseOrderId: 1002,
      receivedDate: "2023-12-05",
      costPerUnit: 3.5,
      quantityReceived: 200,
      quantityRemaining: 150,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2023-12-05T09:00:00Z",
      updatedAt: "2024-01-08T11:20:00Z",
      product: {
        id: 2,
        name: "Paracetamol 650mg",
        sku: "PCT-650",
        genericName: "Acetaminophen",
        manufacturer: "GenMed",
        categoryId: 2,
        defaultSupplierId: 2,
        basePrice: 4.2,
        reorderLevel: 100,
        requiresPrescription: false,
        controlledSubstance: false,
        description: "Pain reliever and fever reducer",
        isActive: true,
        category: {
          id: 2,
          name: "Analgesic",
          description: "Pain relief medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 2,
          name: "PharmGen",
          contactPerson: "Sarah Johnson",
          email: "sarah@pharmgen.com",
          phone: "+1-555-0102",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 2,
        name: "PharmGen",
        contactPerson: "Sarah Johnson",
        email: "sarah@pharmgen.com",
        phone: "+1-555-0102",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 5,
    batchId: 3,
    type: "sale",
    quantity: -82,
    orderId: 5003,
    userId: 3,
    reason: null,
    timestamp: "2024-02-12T15:45:00Z",
    batch: {
      id: 3,
      productId: 2,
      batchNumber: "PCT-2023-001",
      expiryDate: "2025-09-20",
      supplierId: 2,
      purchaseOrderId: 1002,
      receivedDate: "2023-12-05",
      costPerUnit: 3.5,
      quantityReceived: 200,
      quantityRemaining: 68,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2023-12-05T09:00:00Z",
      updatedAt: "2024-02-12T15:45:00Z",
      product: {
        id: 2,
        name: "Paracetamol 650mg",
        sku: "PCT-650",
        genericName: "Acetaminophen",
        manufacturer: "GenMed",
        categoryId: 2,
        defaultSupplierId: 2,
        basePrice: 4.2,
        reorderLevel: 100,
        requiresPrescription: false,
        controlledSubstance: false,
        description: "Pain reliever and fever reducer",
        isActive: true,
        category: {
          id: 2,
          name: "Analgesic",
          description: "Pain relief medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 2,
          name: "PharmGen",
          contactPerson: "Sarah Johnson",
          email: "sarah@pharmgen.com",
          phone: "+1-555-0102",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 2,
        name: "PharmGen",
        contactPerson: "Sarah Johnson",
        email: "sarah@pharmgen.com",
        phone: "+1-555-0102",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 6,
    batchId: 3,
    type: "sale",
    quantity: -50,
    orderId: 5004,
    userId: 2,
    reason: null,
    timestamp: "2024-03-01T10:15:00Z",
    batch: {
      id: 3,
      productId: 2,
      batchNumber: "PCT-2023-001",
      expiryDate: "2025-09-20",
      supplierId: 2,
      purchaseOrderId: 1002,
      receivedDate: "2023-12-05",
      costPerUnit: 3.5,
      quantityReceived: 200,
      quantityRemaining: 18,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2023-12-05T09:00:00Z",
      updatedAt: "2024-03-01T10:15:00Z",
      product: {
        id: 2,
        name: "Paracetamol 650mg",
        sku: "PCT-650",
        genericName: "Acetaminophen",
        manufacturer: "GenMed",
        categoryId: 2,
        defaultSupplierId: 2,
        basePrice: 4.2,
        reorderLevel: 100,
        requiresPrescription: false,
        controlledSubstance: false,
        description: "Pain reliever and fever reducer",
        isActive: true,
        category: {
          id: 2,
          name: "Analgesic",
          description: "Pain relief medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 2,
          name: "PharmGen",
          contactPerson: "Sarah Johnson",
          email: "sarah@pharmgen.com",
          phone: "+1-555-0102",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 2,
        name: "PharmGen",
        contactPerson: "Sarah Johnson",
        email: "sarah@pharmgen.com",
        phone: "+1-555-0102",
        address: null,
        isActive: true,
      },
    },
  },
  // Product 3: Metformin 500mg
  {
    id: 7,
    batchId: 4,
    type: "purchase",
    quantity: 120,
    orderId: null,
    userId: 1,
    reason: "New stock order",
    timestamp: "2024-01-20T08:30:00Z",
    batch: {
      id: 4,
      productId: 3,
      batchNumber: "MET-2024-001",
      expiryDate: "2026-08-10",
      supplierId: 3,
      purchaseOrderId: 1003,
      receivedDate: "2024-01-20",
      costPerUnit: 7.2,
      quantityReceived: 120,
      quantityRemaining: 102,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-01-20T08:30:00Z",
      updatedAt: "2024-01-20T08:30:00Z",
      product: {
        id: 3,
        name: "Metformin 500mg",
        sku: "MET-500",
        genericName: "Metformin HCl",
        manufacturer: "DiabetesCare",
        categoryId: 3,
        defaultSupplierId: 3,
        basePrice: 8.75,
        reorderLevel: 75,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Type 2 diabetes management",
        isActive: true,
        category: {
          id: 3,
          name: "Antidiabetic",
          description: "Diabetes management",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 3,
          name: "GeneriCo",
          contactPerson: "Mike Davis",
          email: "mike@generico.com",
          phone: "+1-555-0103",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 3,
        name: "GeneriCo",
        contactPerson: "Mike Davis",
        email: "mike@generico.com",
        phone: "+1-555-0103",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 8,
    batchId: 4,
    type: "sale",
    quantity: -18,
    orderId: 5005,
    userId: 2,
    reason: null,
    timestamp: "2024-02-05T13:00:00Z",
    batch: {
      id: 4,
      productId: 3,
      batchNumber: "MET-2024-001",
      expiryDate: "2026-08-10",
      supplierId: 3,
      purchaseOrderId: 1003,
      receivedDate: "2024-01-20",
      costPerUnit: 7.2,
      quantityReceived: 120,
      quantityRemaining: 102,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-01-20T08:30:00Z",
      updatedAt: "2024-02-05T13:00:00Z",
      product: {
        id: 3,
        name: "Metformin 500mg",
        sku: "MET-500",
        genericName: "Metformin HCl",
        manufacturer: "DiabetesCare",
        categoryId: 3,
        defaultSupplierId: 3,
        basePrice: 8.75,
        reorderLevel: 75,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Type 2 diabetes management",
        isActive: true,
        category: {
          id: 3,
          name: "Antidiabetic",
          description: "Diabetes management",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 3,
          name: "GeneriCo",
          contactPerson: "Mike Davis",
          email: "mike@generico.com",
          phone: "+1-555-0103",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 3,
        name: "GeneriCo",
        contactPerson: "Mike Davis",
        email: "mike@generico.com",
        phone: "+1-555-0103",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 9,
    batchId: 5,
    type: "purchase",
    quantity: 200,
    orderId: null,
    userId: 1,
    reason: "Bulk order",
    timestamp: "2024-02-28T10:00:00Z",
    batch: {
      id: 5,
      productId: 3,
      batchNumber: "MET-2024-002",
      expiryDate: "2026-10-15",
      supplierId: 3,
      purchaseOrderId: 1006,
      receivedDate: "2024-02-28",
      costPerUnit: 6.8,
      quantityReceived: 200,
      quantityRemaining: 200,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2024-02-28T10:00:00Z",
      updatedAt: "2024-02-28T10:00:00Z",
      product: {
        id: 3,
        name: "Metformin 500mg",
        sku: "MET-500",
        genericName: "Metformin HCl",
        manufacturer: "DiabetesCare",
        categoryId: 3,
        defaultSupplierId: 3,
        basePrice: 8.75,
        reorderLevel: 75,
        requiresPrescription: true,
        controlledSubstance: false,
        description: "Type 2 diabetes management",
        isActive: true,
        category: {
          id: 3,
          name: "Antidiabetic",
          description: "Diabetes management",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 3,
          name: "GeneriCo",
          contactPerson: "Mike Davis",
          email: "mike@generico.com",
          phone: "+1-555-0103",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 3,
        name: "GeneriCo",
        contactPerson: "Mike Davis",
        email: "mike@generico.com",
        phone: "+1-555-0103",
        address: null,
        isActive: true,
      },
    },
  },
  // Product 4: Omeprazole 20mg
  {
    id: 10,
    batchId: 6,
    type: "purchase",
    quantity: 100,
    orderId: null,
    userId: 1,
    reason: "Regular restock",
    timestamp: "2023-11-15T09:00:00Z",
    batch: {
      id: 6,
      productId: 4,
      batchNumber: "OMZ-2023-001",
      expiryDate: "2025-06-30",
      supplierId: 1,
      purchaseOrderId: 1004,
      receivedDate: "2023-11-15",
      costPerUnit: 12.5,
      quantityReceived: 100,
      quantityRemaining: 85,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2023-11-15T09:00:00Z",
      updatedAt: "2023-11-15T09:00:00Z",
      product: {
        id: 4,
        name: "Omeprazole 20mg",
        sku: "OMZ-020",
        genericName: "Omeprazole",
        manufacturer: "GastroMed",
        categoryId: 4,
        defaultSupplierId: 1,
        basePrice: 15.0,
        reorderLevel: 60,
        requiresPrescription: false,
        controlledSubstance: false,
        description: "Proton pump inhibitor for acid reflux",
        isActive: true,
        category: {
          id: 4,
          name: "GI",
          description: "Gastrointestinal medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
  {
    id: 11,
    batchId: 6,
    type: "sale",
    quantity: -15,
    orderId: 5006,
    userId: 3,
    reason: null,
    timestamp: "2024-01-22T16:30:00Z",
    batch: {
      id: 6,
      productId: 4,
      batchNumber: "OMZ-2023-001",
      expiryDate: "2025-06-30",
      supplierId: 1,
      purchaseOrderId: 1004,
      receivedDate: "2023-11-15",
      costPerUnit: 12.5,
      quantityReceived: 100,
      quantityRemaining: 85,
      locationId: 1,
      status: "available",
      notes: null,
      createdAt: "2023-11-15T09:00:00Z",
      updatedAt: "2024-01-22T16:30:00Z",
      product: {
        id: 4,
        name: "Omeprazole 20mg",
        sku: "OMZ-020",
        genericName: "Omeprazole",
        manufacturer: "GastroMed",
        categoryId: 4,
        defaultSupplierId: 1,
        basePrice: 15.0,
        reorderLevel: 60,
        requiresPrescription: false,
        controlledSubstance: false,
        description: "Proton pump inhibitor for acid reflux",
        isActive: true,
        category: {
          id: 4,
          name: "GI",
          description: "Gastrointestinal medications",
          parentCategoryId: null,
        },
        defaultSupplier: {
          id: 1,
          name: "MedSupply Co",
          contactPerson: "John Smith",
          email: "john@medsupply.com",
          phone: "+1-555-0101",
          address: null,
          isActive: true,
        },
      },
      supplier: {
        id: 1,
        name: "MedSupply Co",
        contactPerson: "John Smith",
        email: "john@medsupply.com",
        phone: "+1-555-0101",
        address: null,
        isActive: true,
      },
    },
  },
];

/**
 * Fetch transactions for a specific product
 * TODO: Replace with actual API call
 *
 * @throws {Error} If data validation fails
 */
export async function fetchTransactionsByProductId(
  productId: number,
): Promise<StockTransactionWithRelations[]> {
  await new Promise((resolve) => setTimeout(resolve, 200));

  // Filter transactions by product ID through batch relation
  const transactions = MOCK_TRANSACTIONS.filter(
    (t) => t.batch.productId === productId,
  );

  // Validate data with Zod schema
  const result =
    stockTransactionsWithRelationsArraySchema.safeParse(transactions);

  if (!result.success) {
    console.error("Transaction data validation failed:", result.error);
    throw new Error("Invalid transaction data format");
  }

  return result.data;
}
