/**
 * Staff module mock data
 * Extracted from StaffManagementStudio mockup
 */

import { Moon, Sunrise, Sunset } from "lucide-react";
import type { AttRecord, LeaveReq, ShiftTemplate, Staff } from "./types";

export const STAFF_DATA: Staff[] = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    role: "Pharmacist",
    email: "s.chen@rxpharmacy.com",
    phone: "+1 (555) 001-0001",
    avatar: "",
    initials: "SC",
    dutyStatus: "On Duty",
    clockedIn: "08:30 AM",
    hoursThisWeek: 32,
    credentials: [
      {
        type: "Pharmacist License",
        number: "PH-****-4892",
        expiry: "Dec 31, 2025",
        status: "expiring",
        daysLeft: 279,
      },
      {
        type: "DEA Registration",
        number: "DE-****-1120",
        expiry: "Mar 15, 2026",
        status: "valid",
        daysLeft: 354,
      },
      {
        type: "CPR Certification",
        number: "CP-****-0091",
        expiry: "Jun 1, 2025",
        status: "critical",
        daysLeft: 67,
      },
    ],
    competencies: ["Immunizations", "Compounding", "MTM"],
    lastActive: "Now",
    complianceScore: 88,
    branch: "Main Street",
    otHours: 2.5,
    punctualityScore: 96,
    leaveBalance: 12,
  },
  {
    id: "2",
    name: "Marcus Williams",
    role: "Technician",
    email: "m.williams@rxpharmacy.com",
    phone: "+1 (555) 002-0002",
    avatar: "",
    initials: "MW",
    dutyStatus: "On Break",
    clockedIn: "09:00 AM",
    hoursThisWeek: 28,
    credentials: [
      {
        type: "Pharmacy Tech License",
        number: "PT-****-7731",
        expiry: "Aug 22, 2025",
        status: "critical",
        daysLeft: 149,
      },
      {
        type: "Controlled Sub Training",
        number: "CS-****-3340",
        expiry: "Jan 10, 2026",
        status: "valid",
        daysLeft: 290,
      },
    ],
    competencies: ["Dispensing", "IV Prep"],
    lastActive: "12 min ago",
    complianceScore: 75,
    branch: "Main Street",
    otHours: 0,
    punctualityScore: 78,
    leaveBalance: 8,
  },
  {
    id: "3",
    name: "Priya Sharma",
    role: "Manager",
    email: "p.sharma@rxpharmacy.com",
    phone: "+1 (555) 003-0003",
    avatar: "",
    initials: "PS",
    dutyStatus: "On Duty",
    clockedIn: "07:45 AM",
    hoursThisWeek: 40,
    credentials: [
      {
        type: "Pharmacist License",
        number: "PH-****-2281",
        expiry: "Nov 14, 2026",
        status: "valid",
        daysLeft: 598,
      },
      {
        type: "DEA Registration",
        number: "DE-****-8870",
        expiry: "Sep 30, 2026",
        status: "valid",
        daysLeft: 553,
      },
      {
        type: "HIPAA Cert",
        number: "HP-****-0012",
        expiry: "Apr 5, 2025",
        status: "expired",
        daysLeft: -10,
      },
    ],
    competencies: ["Immunizations", "Compounding", "Counseling", "MTM"],
    lastActive: "Now",
    complianceScore: 95,
    branch: "Main Street",
    otHours: 3.0,
    punctualityScore: 99,
    leaveBalance: 18,
  },
  {
    id: "4",
    name: "James O'Brien",
    role: "Technician",
    email: "j.obrien@rxpharmacy.com",
    phone: "+1 (555) 004-0004",
    avatar: "",
    initials: "JO",
    dutyStatus: "Off Duty",
    clockedIn: null,
    hoursThisWeek: 16,
    credentials: [
      {
        type: "Pharmacy Tech License",
        number: "PT-****-5503",
        expiry: "Feb 28, 2026",
        status: "valid",
        daysLeft: 339,
      },
    ],
    competencies: ["Dispensing"],
    lastActive: "2 hours ago",
    complianceScore: 100,
    branch: "Main Street",
    otHours: 0,
    punctualityScore: 100,
    leaveBalance: 14,
  },
  {
    id: "5",
    name: "Linda Park",
    role: "Pharmacist",
    email: "l.park@rxpharmacy.com",
    phone: "+1 (555) 005-0005",
    avatar: "",
    initials: "LP",
    dutyStatus: "Off Duty",
    clockedIn: null,
    hoursThisWeek: 36,
    credentials: [
      {
        type: "Pharmacist License",
        number: "PH-****-9021",
        expiry: "Jul 4, 2025",
        status: "critical",
        daysLeft: 99,
      },
      {
        type: "DEA Registration",
        number: "DE-****-4430",
        expiry: "Dec 18, 2025",
        status: "expiring",
        daysLeft: 266,
      },
    ],
    competencies: ["Immunizations", "Counseling"],
    lastActive: "Yesterday",
    complianceScore: 82,
    branch: "Main Street",
    otHours: 4.0,
    punctualityScore: 85,
    leaveBalance: 6,
  },
];

export const SHIFT_TEMPLATES: ShiftTemplate[] = [
  {
    id: "morning",
    name: "Morning",
    icon: Sunrise,
    start: "8:00 AM",
    end: "4:00 PM",
    color: "#835400",
    bg: "#FFF4CE",
    border: "#F8E0A0",
  },
  {
    id: "evening",
    name: "Evening",
    icon: Sunset,
    start: "4:00 PM",
    end: "12:00 AM",
    color: "#0078D4",
    bg: "#EFF6FC",
    border: "#C7E2F5",
  },
  {
    id: "night",
    name: "Night",
    icon: Moon,
    start: "12:00 AM",
    end: "8:00 AM",
    color: "#7B61FF",
    bg: "#F4EBFF",
    border: "#D4BBFF",
  },
];

export const ATTENDANCE_RECORDS: AttRecord[] = [
  {
    staffId: "1",
    date: "Today",
    scheduledStart: "8:00 AM",
    scheduledEnd: "4:00 PM",
    actualIn: "8:28 AM",
    actualOut: null,
    breakMins: 30,
    status: "present",
    hoursWorked: 6.5,
    otHours: 0,
    note: "",
  },
  {
    staffId: "2",
    date: "Today",
    scheduledStart: "9:00 AM",
    scheduledEnd: "5:00 PM",
    actualIn: "9:03 AM",
    actualOut: null,
    breakMins: 45,
    status: "present",
    hoursWorked: 5.5,
    otHours: 0,
    note: "",
  },
  {
    staffId: "3",
    date: "Today",
    scheduledStart: "7:30 AM",
    scheduledEnd: "3:30 PM",
    actualIn: "7:44 AM",
    actualOut: null,
    breakMins: 30,
    status: "present",
    hoursWorked: 7.3,
    otHours: 0,
    note: "",
  },
  {
    staffId: "4",
    date: "Today",
    scheduledStart: "2:00 PM",
    scheduledEnd: "10:00 PM",
    actualIn: null,
    actualOut: null,
    breakMins: 0,
    status: "absent",
    hoursWorked: 0,
    otHours: 0,
    note: "Day off",
  },
  {
    staffId: "5",
    date: "Today",
    scheduledStart: "8:00 AM",
    scheduledEnd: "4:00 PM",
    actualIn: null,
    actualOut: null,
    breakMins: 0,
    status: "absent",
    hoursWorked: 0,
    otHours: 0,
    note: "Sick leave",
  },
  {
    staffId: "1",
    date: "Yesterday",
    scheduledStart: "8:00 AM",
    scheduledEnd: "4:00 PM",
    actualIn: "7:58 AM",
    actualOut: "4:32 PM",
    breakMins: 30,
    status: "present",
    hoursWorked: 8.5,
    otHours: 0.5,
    note: "",
  },
  {
    staffId: "2",
    date: "Yesterday",
    scheduledStart: "9:00 AM",
    scheduledEnd: "5:00 PM",
    actualIn: "9:18 AM",
    actualOut: "5:00 PM",
    breakMins: 45,
    status: "late",
    hoursWorked: 7.7,
    otHours: 0,
    note: "Late arrival — 18 min",
  },
  {
    staffId: "3",
    date: "Yesterday",
    scheduledStart: "7:30 AM",
    scheduledEnd: "3:30 PM",
    actualIn: "7:30 AM",
    actualOut: "5:15 PM",
    breakMins: 30,
    status: "present",
    hoursWorked: 9.25,
    otHours: 1.75,
    note: "",
  },
  {
    staffId: "4",
    date: "Yesterday",
    scheduledStart: "2:00 PM",
    scheduledEnd: "10:00 PM",
    actualIn: "2:00 PM",
    actualOut: "10:00 PM",
    breakMins: 30,
    status: "present",
    hoursWorked: 7.5,
    otHours: 0,
    note: "",
  },
  {
    staffId: "5",
    date: "Yesterday",
    scheduledStart: "8:00 AM",
    scheduledEnd: "4:00 PM",
    actualIn: "8:05 AM",
    actualOut: "2:45 PM",
    breakMins: 30,
    status: "early_departure",
    hoursWorked: 6.17,
    otHours: 0,
    note: "Left early — 75 min",
  },
];

export const LEAVE_REQUESTS: LeaveReq[] = [
  {
    id: "l1",
    staffId: "5",
    type: "Sick Leave",
    startDate: "Mar 26",
    endDate: "Mar 27",
    days: 2,
    reason: "Feeling unwell, doctor visit",
    status: "approved",
    submittedOn: "Mar 25",
  },
  {
    id: "l2",
    staffId: "2",
    type: "Vacation",
    startDate: "Apr 5",
    endDate: "Apr 9",
    days: 5,
    reason: "Family trip — booked in advance",
    status: "pending",
    submittedOn: "Mar 20",
  },
  {
    id: "l3",
    staffId: "4",
    type: "Personal",
    startDate: "Mar 26",
    endDate: "Mar 26",
    days: 1,
    reason: "Personal errand",
    status: "approved",
    submittedOn: "Mar 24",
  },
  {
    id: "l4",
    staffId: "1",
    type: "Vacation",
    startDate: "Apr 15",
    endDate: "Apr 18",
    days: 4,
    reason: "Spring break travel",
    status: "pending",
    submittedOn: "Mar 22",
  },
  {
    id: "l5",
    staffId: "3",
    type: "Emergency",
    startDate: "Mar 15",
    endDate: "Mar 15",
    days: 1,
    reason: "Family emergency",
    status: "approved",
    submittedOn: "Mar 15",
  },
  {
    id: "l6",
    staffId: "2",
    type: "Sick Leave",
    startDate: "Feb 10",
    endDate: "Feb 12",
    days: 3,
    reason: "Flu — medical certificate attached",
    status: "approved",
    submittedOn: "Feb 10",
  },
];
